//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FitbitSDK
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class APIAccess
	{
		public virtual Units Units
		{
			get;
			set;
		}

		public virtual RequestResult RequestResult
		{
			get;
			set;
		}

		public APIAccess()
		{
		}

	}
}

