// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SharpFit.Resources.BodyInfo.Weight
{

    internal class Goal
    {

        [JsonProperty("startDate")]
        public string StartDate { get; set; }

        [JsonProperty("startWeight")]
        public int StartWeight { get; set; }

        [JsonProperty("weight")]
        public int Weight { get; set; }
    }

}
