// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SharpFit.Resources.BodyInfo.Fat
{

    internal class Goal
    {

        [JsonProperty("fat")]
        public int Fat { get; set; }
    }

}
